### ISSUE TITLE
Backend : Create Debate :  Create debate for Three Days but on debate block showing 2 days left

### ISSUE THREAD

**Issue by arguly-chandra-kiran** [khanabdul/arguly#17]
Expected : 

if 70hr is remaining than show "3 days left".
if 50hr is remaining than show "3 days left".
if 36hr is remaining than show "2 days left".
if 23hr is remaining than show "23 hour left".
if 5hr is remaining than show "5 hour left".

**Comment by khanabdul** [comment]
done using cieling.
