### ISSUE TITLE
Backend : Anonymous user always go to Home page after login 

### ISSUE THREAD

**Issue by arguly-chandra-kiran** [khanabdul/arguly#25]
Steps to reproduce:
Without login go to Issues Page:
Click on any issues.
Click on any user on People with similar interests.
Login with the credential.

Actual : 
User redirect to the home page.

Expected:
 User should go to the Issues index page.

**Comment by khanabdul** [comment]
anonymous user -hide people card

**Comment by khanabdul** [comment]
done
